In [1]:
#pip install numpy
import numpy as np

In [22]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[4,5,6,7]])
arr3=np.array([[[10,20], [30,40], [50,60], [70,80]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)




1
2
3


In [15]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


In [19]:
np.ones(4)


array([1., 1., 1., 1.])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [27]:
arr1.shape=(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [28]:
arr1.sum()

10

In [29]:
arr1.sum(axis=0)  #axis=0 -->on every column  

array([4, 6])

In [31]:
arr1.max(axis=1)   # axis=1 --> on every row

array([2, 4])

In [32]:
arr1+5  # 5 is added to every element

array([[6, 7],
       [8, 9]])

In [37]:
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6],[7,8]])
arr3*arr4

array([[ 5, 12],
       [21, 32]])

In [38]:
arr3.dot(arr4)

array([[19, 22],
       [43, 50]])

In [39]:
arr3[0,1]  #row ,column

2

In [40]:
arr3[0][1] #row ,column

2