In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 14.8/14.8 MB 5.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import numpy as np

In [4]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
a=np.arange(4,12)
print(a)
print(a.shape)

[ 4  5  6  7  8  9 10 11]
(8,)


In [11]:
a=np.arange(4,26,3)
print(a)
print(a.shape)

[ 4  7 10 13 16 19 22 25]
(8,)


In [12]:
d=a.reshape(2,4)
print(d)

[[ 4  7 10 13]
 [16 19 22 25]]


In [13]:
b=np.arange(50)
b=b[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [17]:
z=np.arange(10).reshape(5,2)
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
#finding the indeces of non zero elements
nz=np.nonzero([1,0,0,2,50,5,8])
print(nz)

(array([0, 3, 4, 5, 6], dtype=int64),)


In [23]:
#identity matrix
mt=np.eye(3)
print(mt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
rd=np.random.random((3,3,3))
print(rd)

[[[0.0408353  0.29638048 0.86547052]
  [0.73621237 0.24804231 0.34118757]
  [0.7054053  0.6942583  0.66306891]]

 [[0.76300427 0.0291937  0.01018779]
  [0.73030494 0.9266716  0.20640946]
  [0.1762269  0.76666821 0.63308745]]

 [[0.08181326 0.62930115 0.50209949]
  [0.75468631 0.39280413 0.55887218]
  [0.39742484 0.95325961 0.18668946]]]


In [35]:
na=np.random.random((10))
na=na.mean()
print(na)

0.5037175606950004


In [40]:
import pandas as pd
#dataframe into numpy array

df=pd.DataFrame({'a1':[1,2,3],'a2':[4,5,6]},index=['X', 'Y', 'Z'])
print("DataFrame:")
print(df)

x=df.to_numpy()
print("\n dataframe to numpy")
print(x)

y=df.index.to_numpy()
print("\n dataframe indexes numpy")
print(y)







DataFrame:
   a1  a2
X   1   4
Y   2   5
Z   3   6

 dataframe to numpy
[[1 4]
 [2 5]
 [3 6]]

 dataframe indexes numpy
['X' 'Y' 'Z']


In [42]:
x=np.array([[1,2],
            [3,4],
            [5,6]])
print("numpy array\n")
print(x)

y=x[:,0] #first column in all rows
print("fist column in all rows")
print(x)

z=x[1,:] #second row with all columns
print(z)


numpy array

[[1 2]
 [3 4]
 [5 6]]
fist column in all rows
[[1 2]
 [3 4]
 [5 6]]
[3 4]


In [44]:
yesterday=np.datetime64('today','D') - np.timedelta64(1,'D')
today=np.datetime64('today','D')
tommorrow=np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tommorrow)

2023-01-24
2023-01-25
2023-01-26


In [55]:
z=np.arange("2023-01-25","2024-03-25",dtype='datetime64[Y]')
print(z)

['2023']


In [56]:
z=np.linspace(0,1,11,endpoint=False)
print(z)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


In [58]:
z=np.random.random(10)
z.sort()
print(z)

[0.03976536 0.42928966 0.58094061 0.58645347 0.67525981 0.70426834
 0.72742397 0.72821016 0.73977997 0.92281428]


In [60]:
import matplotlib.pyplot as plt
import seaborn as sns

In [62]:
print(pd.__version__)
print(sns.__version__)

1.5.3
0.12.2


In [70]:
df_zomato=pd.read_csv('C:\\Users\\miles\\Documents\\GitHub\\Training_futurense\\Python\\pandas\\lecture notes\\zomato.csv',encoding='latin1')

df_zomato.head(3)

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  

[3 rows x 21 columns]

In [68]:
df_countrycode=pd.read_excel('C:\\Users\\miles\\Documents\\GitHub\\Training_futurense\\Python\\pandas\\lecture notes\\Country-Code.xlsx')
df_countrycode.head(10)

Country Code       Country
0             1         India
1            14     Australia
2            30        Brazil
3            37        Canada
4            94     Indonesia
5           148   New Zealand
6           162   Phillipines
7           166         Qatar
8           184     Singapore
9           189  South Africa

In [77]:
print(df_zomato.index)
print(df_zomato.shape)
print(df_zomato.info())


RangeIndex(start=0, stop=9551, step=1)
(9551, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  Average Cost for two  9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     

In [78]:
print(df_zomato.memory_usage(deep=True))

Index                       128
Restaurant ID             76408
Restaurant Name          691807
Country Code              76408
City                     623626
Address                 1057921
Locality                 679199
Locality Verbose         776936
Longitude                 76408
Latitude                  76408
Cuisines                 734354
Average Cost for two      76408
Currency                 712379
Has Table booking        564667
Has Online delivery      565960
Is delivering now        563543
Switch to order menu     563509
Price range               76408
Aggregate rating          76408
Rating color             599132
Rating text              611462
Votes                     76408
dtype: int64


In [81]:
print(df_zomato.shape)
df_zomato.drop(columns=['Longitude', 'Latitude'],axis=1,inplace=True)  # axis=1 columns   -- axis=0 rows
print(df_zomato.shape)


(9551, 21)
(9551, 19)


In [83]:
# joining two dataframes

join_df = pd.merge(
                    left=df_zomato,
                    right=df_countrycode,
                    left_on='Country Code',
                    right_on='Country Code',
                    how='inner'

)
join_df.head(2)

Restaurant ID   Restaurant Name  Country Code         City  \
0        6317637  Le Petit Souffle           162  Makati City   
1        6304287  Izakaya Kikufuji           162  Makati City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   

                                    Locality Verbose  \
0  Century City Mall, Poblacion, Makati City, Mak...   
1  Little Tokyo, Legaspi Village, Makati City, Ma...   

                     Cuisines  Average Cost for two          Currency  \
0  French, Japanese, Desserts                  1100  Botswana Pula(P)   
1                    Japanese                  1200  Botswana Pula(P)   

  Has Table booking Has Online delivery Is delivering now  \
0               Yes                  No                No   
1               Yes                  No                No   

  Switch to order menu  Price range  Aggregate rating Rating color  \
0                   No            3               4.8   Dark Green   
1                   No            3               4.5   Dark Green   

  Rating text  Votes      Country  
0   Excellent    314  Phillipines  
1   Excellent    591  Phillipines